fix: reinstate the old KsqlRestClient.create overload
Commit a33b1e68426ae61fb8bf45c267f198d3eb3d6ff3
has changed the `create` method signature without
deprecating the old one first, causing the drift benchmarks
to fail with:
```
java.lang.NoSuchMethodError: io.confluent.ksql.rest.client.KsqlRestClient.create(
	java/lang/String;
	java/util/Map;
	java/util/Map;
	java/util/Optional;
)
io/confluent/ksql/rest/client/KsqlRestClient;
```
We're just adding back the missing signagure