fix: use args map instead of method args in generated java code (#9711)
Fixes https://github.com/confluentinc/ksql/issues/9353

When generating java from ksql, all arguments are passed as individual method arguments. The java compiler only allows up to 255 method arguments. After a ksql statement reaches a certain size, this limit is nolonger sufficient resulting in the following ClassFormatError:

Exception in thread "main" java.lang.ClassFormatError: Too many arguments in method signature in class file SC at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) at org.codehaus.janino.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:74) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:317) at org.codehaus.janino.ScriptEvaluator.cook2(ScriptEvaluator.java:608) at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:597) at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:534) at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:503) at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:204) at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:80) at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:75) at io.confluent.ksql.execution.codegen.CodeGenRunner.cook(CodeGenRunner.java:195) ... 

This change puts all those arguments in one map. This map is then passed as one method argument.