fix: configure KsqlBoundedMemoryConfigSetter in StandaloneExecutor mode (#10178)
We missed to call method configure on the KsqlBoundedMemoryConfigSetter
when ksql is started with --queries-file. That resulted in

java.lang.IllegalStateException: Cannot use KsqlBoundedMemoryRocksDBConfigSetter before it's been configured.

This PR adds the missing call.

Github issue: https://github.com/confluentinc/ksql/issues/10121