test: fix NPE in SQL tester on missing tombstone (#6495)
The SQL testing tool throws an NPE from any tombstone assert that fails, e.g.

```sql
ASSERT NULL VALUES b (id) KEY (1);
```

This change fixes that. Output is:

```
io.confluent.ksql.test.KsqlTestException: Test failure for assert `ASSERT NULL VALUES B (ID) KEY (1)` (Line: 74, Col: 20):
	Expected record does not match actual.
+------------------+------------------+------------------+------------------+---------------+
|.                 |ROWTIME           |ID                |COL1              |COL2           |
+------------------+------------------+------------------+------------------+---------------+
|EXPECTED          |1                 |1603378499234     |<TOMBSTONE>       |<TOMBSTONE>    |
|ACTUAL            |1                 |1603378499234     |1                 |2              |

	file:///Users/andy/dev/github.com/confluentinc/ksql_2/ksqldb-functional-tests/target/test-classes/sql-tests/query-upgrades/filters.sql:247

	at io.confluent.ksql.test.driver.KsqlTesterTest.handleExpectedException(KsqlTesterTest.java:393)
	...
```

Co-authored-by: Andy Coates <big-andy-coates@users.noreply.github.com>