test: improve error msg & remove log spam
This change improves the error message returned by the testing tool & QTT when a test case is expected to throw an exception but doesn't.

Old message was:

```
java.lang.AssertionError: test did not generate any queries.
expected: non-empty collection
was: Collection[]
failed test: key-schemas - KEY key field name
in file: query-validation-tests/key-schemas.json

```

New message is:

```
java.lang.AssertionError: Expected test to throw(an instance of io.confluent.ksql.util.KsqlStatementException and statement text a string containing "CREATE STREAM INPUT (KEY STRING KEY, ID bigint) WITH (kafka_topic='input',value_format='JSON');" and exception with message a string containing "'KEY' is an invalid KEY column name. KSQL currently only supports KEY columns named ROWKEY.")
failed test: key-schemas - KEY key field name
in file: query-validation-tests/key-schemas.json
```

Plus this change suppresses the logging of `ProtobufDataConfig` creation in the tests, which is just noise and fills up the logs on the build servers