fix: exception on shutdown of ksqlDB server
On shutdown we're trying to close the Kafka Consumer from a different thread to the one that is using the consumer. Kafka Consumers are single threaded.
Hence we must close the consumer on the same thread as the one polling.

Fixes the following exception on shutdown:

```
[2020-02-07 15:10:44,646] ERROR Exception while waiting for CommandRunner thread to complete (io.confluent.ksql.rest.server.KsqlRestApplication:350)
    java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
    at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2422)
    at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2305)
    at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2260)
    at io.confluent.ksql.rest.server.CommandTopic.close(CommandTopic.java:121)
    at io.confluent.ksql.rest.server.computation.CommandStore.close(CommandStore.java:143)
    at io.confluent.ksql.rest.server.computation.CommandRunner.close(CommandRunner.java:148)
    at io.confluent.ksql.rest.server.KsqlRestApplication.triggerShutdown(KsqlRestApplication.java:348)
    at io.confluent.ksql.rest.server.ExecutableServer.triggerShutdown(ExecutableServer.java:54)
    at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:80)
    at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:61)
 ```